micronaut:
  application:
    name: micronautTransactionIssue

datasources:
  default:
    url: jdbc:h2:mem:testDb;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:create.sql'
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
    min-pool-size: 10
